"""add status to participants

Revision ID: 742918d5a9bc
Revises: 13abfc273683
Create Date: 2026-08-01 11:22:49.831140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742918d5a9bc'
down_revision: Union[str, Sequence[str], None] = '13abfc273683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'status')
    # ### end Alembic commands ###
